# Generated by Django 6.0 on 2025-12-06 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre del autor', max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Introduce cuándo nació el autor si lo conoces', null=True)),
                ('death_date', models.DateField(blank=True, help_text='Introduce la fecha de fallecimiento si la conoces', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre del género', max_length=200, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre del idioma', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Introduce el título del libro', max_length=200)),
                ('isbn', models.CharField(help_text='Introduce el ISBN del libro', max_length=13)),
                ('summary', models.TextField(help_text='Introduce el resumen del libro', max_length=100, verbose_name='descripción')),
                ('author', models.ForeignKey(blank=True, help_text='Introduce el autor del libro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='librosaut', to='catalog.author')),
                ('genre', models.ManyToManyField(help_text='Introduce el género del libro', related_name='librosgen', to='catalog.genre')),
                ('original_language', models.ForeignKey(help_text='Introduce el idioma original del libro', on_delete=django.db.models.deletion.RESTRICT, related_name='librosidiom', to='catalog.language')),
            ],
            options={
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance')], default='m', help_text='Introduce el estado del ejemplar', max_length=1)),
                ('imprint', models.CharField(help_text='Introduce los detalles de esta edición', max_length=100)),
                ('due_back', models.DateField(blank=True, help_text='Introduce la fecha de devolución del préstamo', null=True)),
                ('book', models.ForeignKey(help_text='Introduce el libro al que pertenece el ejemplar', on_delete=django.db.models.deletion.RESTRICT, related_name='instancias', to='catalog.book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
