# Generated by Django 6.0.1 on 2026-01-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Librarian can mark bookinstance as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(help_text='Introduce el libro al que pertenece el ejemplar', on_delete=django.db.models.deletion.RESTRICT, to='catalog.book'),
        ),
    ]
