# Generated by Django 6.0.2 on 2026-02-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_perfil_permisoe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('permitir', 'A este usuario le permito'),)},
        ),
    ]
