# Generated by Django 6.0.2 on 2026-02-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='permisos',
            field=models.ManyToManyField(to='catalog.permisoe'),
        ),
    ]
