# Generated by Django 6.0.2 on 2026-02-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_perfil_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Librarian can mark bookinstance as returned'), ('prestalibro', 'Puede prestar un libro'))},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('permitir', 'A este usuario le permito'), ('penalizaciones', 'A este usuario se le permite modificar penalizaciones'))},
        ),
    ]
